title: Yifei Huang
description: My Homepage
author: Yifei Huang
logo: /static/img/IMG_6842.JPG
github: https://github.com/hyf015
about: Project assistant professor @ UTokyo

baseurl: "/"
url: "/"

allowsearch: true

disqus_shortname: 
google_analytics: UA-122681435-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "proj/index.html"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
